development:
  adapter: mysql2
  database: sinsa
  host: localhost
  username: root
  port: 3306
  password:
  secure_auth: false
  pool: 35
  timeout: 300000
  strict: false



production:
  adapter: mysql2
  encoding: utf8mb4
  database: sinsa
  username: root
  password: q1w2e3r4
  host: localhost
  port: 3306
  secure_auth: false
  pool: 35
  timeout: 300000
  strict: false

